# Generated by Django 4.1.2 on 2022-10-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0003_alter_department_major'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name_plural': 'Duties'},
        ),
    ]
