# Generated by Django 4.1.2 on 2022-10-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0005_duty_weigt_alter_department_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='date_employment',
            field=models.DateField(),
        ),
    ]
