# Generated by Django 4.1.2 on 2022-10-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0006_alter_employer_date_employment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='weigt',
            new_name='weight',
        ),
    ]
